### PR TITLE
Fixed css and html for Australia

### PR DESCRIPTION
**Pull request by siprachanh**
# Description
Australia.html and css file changes
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions
test link

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by karlarn** [comment]
Good to go.

**Comment by eo-lind** [comment]
👍  looks good

**Comment by rushayhays** [comment]
Lookin good

**Review by karlarn — APPROVED** [review]
looks good

**Review by eo-lind — APPROVED** [review]
Changes look good

**Pull request merged**
